#!/bin/bash

# Set up environment variables
export GOOGLE_API_KEY="GAK"
export GOOGLE_DEFAULT_CLIENT_ID="GDCI"
export GOOGLE_DEFAULT_CLIENT_SECRET="GDCS"

# Launch Chromium
INSTALL_PATH/Chromium_orig_bin
